[package]
name = "axum-sso"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing-subscriber = { version = "0" }
tokio = { version = "1", features = ["full"] }
axum = { version = "0" }
